# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZL8DvIE8_ctnAQKeXMiU8cfqRX8_6JLQ
"""



##             Example :  [7 ,2 ,5 ,10 ,8  ] | m = 2 
##                        [7] [2 ,5 ,10 ,8 ] = [7 , 25]
##                        [7 ,2] [5 ,10 ,8 ] = [9 , 23]
##                        [7 ,2 ,5] [10 ,8 ] = [14 , 18]
##                        [7 ,2 ,5 ,10] [8 ] = [24 , 8] 

def splitArray (nums,m):
  lo = max(nums) #collect largest sum that is not exceed mid and find range
  hi = sum(nums) #subarray require

  while lo < hi:

    mid = (lo+hi)//2
    total = 0
    count = 1

    for i in nums:
      if total + i <= mid:
        total += i
      else:
        total = i
        count += 1
    if count > m:
      lo = mid + 1
    else:
      hi = mid

  return hi

nums = [7 ,2 ,5 ,10 ,8 ]
m = 2

print("result is : ",splitArray(nums,m))